server:
#  port: 9090
  servlet:
    context-path: /auth
spring:
#  application:
#    name: smartgovernment-auth
  redis:
    database: 0
    host: 192.168.106.101
    port: 6379
    password:
    jedis:
      pool:
        max-idle: 8
        max-wait: 3000
        max-active: 8
        min-idle: 0
    timeout: 5000

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_user?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
 #服务发现
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
auth:
  tokenValiditySeconds: 3600  #token存储到redis的过期时间
  clientId: SmartGovernment
  clientSecret: SmartGovernment
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/sg.keystore
    secret: smartgovernmentkeystore
    alias: sgkey
    password: smartgovernment






