#server:
#  port: 12000

spring:
#  application:
#    name: smartgovernment-filemanagecentre
  data:
    mongodb:
      database: zxs_smartgovernment
      host: 192.168.106.101
      port: 27017

  redis:
    database: 0
    # Redis服务器地址 127.0.0.1 /192.168.117.57 / 172.20.14.163  /10.17.76.101/ 192.168.106.101
    host: 192.168.106.101
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 30000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 1
  #数据库配置
  datasource:
    url:  jdbc:mysql://localhost:3306/zxs_filecentre?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 1000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    logSlowSql: true
   # druid:
   #   login:
   #     username:  admin
    #    password:  123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  multipart:
    maxFileSize: 524288000    #500M
    maxRequestSize: 1073741024   #1024Mb
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#mybatisplus配置
mybatis-plus:
  config-location: classpath:mapper/sqlConfig.xml
  mapper-locations: classpath*:mapper/filecentre/*.xml
  type-aliases-package: com.neco.filemanagecentre.model
  global-config:
    id-type: 2
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页插件配置
pageInterceptor:
  # mysql oracle
  dialectType: mysql
  localPage: true

#开启请求收集日志
sg:
  log:
    enable: true

#fasfDFS配置
fdfs:
  so-timeout: 2000 # 超时时间
  connect-timeout: 3000 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.106.101:22122
  web-server-url: http://192.168.106.101:80/


#大文件配置
bigFile:
  localPath: /data/smartgovernment/bigFile/