server:
  port: 9999
spring:
  application:
    name: smartgovernment-apigateway
  redis:
    database: 0
    # Redis服务器地址 127.0.0.1 /192.168.117.57 / 172.20.14.163  /10.17.76.101/ 192.168.106.101
    host: 192.168.106.101
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 30000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true  #让gateway可以发现nacos中的微服务
      routes:
        - id: filemanagecentre_route
          uri: lb://smartgovernment-filemanagecentre   # lb指的是从nacos中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/filemanagecentre/**
          filters:
            - StripPrefix=1

filter:
  excludeUrl: /auth/userlogin,/auth/userlogout,/openfile/list,/openfile/downloadFile,/openfile/batchDownloadFiles

auth:
  tokenValiditySeconds: 3600  #token存储到redis的过期时间

